---

- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: include logstash.yml
  include: logstash.yml
  tags:
    - install

- name: include logstash-config.yml
  include: logstash-config.yml
  tags:
    - config

- name: Make sure Logstash is started
  service:
    name: logstash
    state: started
    enabled: true
