---

- name: include logstash.yml
  include: logstash.yml
  tags:
    - install

- name: include logstash-config.yml
  include: logstash-config.yml
  tags:
    - config

- name: Make sure Logstash is started
  service:
    name: logstash
    state: started
    enabled: true
  when: logstash_start_service
