---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1404
    image: geerlingguy/docker-ubuntu1404-ansible:latest
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: true
    volume_mounts:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
